/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppUploadRouteImport } from './routes/app/upload'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppNotesRouteImport } from './routes/app/notes'
import { Route as AppJobleadsRouteImport } from './routes/app/jobleads'
import { Route as AppInterviewsRouteImport } from './routes/app/interviews'
import { Route as AppDocumentsRouteImport } from './routes/app/documents'
import { Route as AppApplicationsRouteImport } from './routes/app/applications'
import { Route as AppApplicationRouteImport } from './routes/app/application'
import { Route as AppAddapplicationRouteImport } from './routes/app/addapplication'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUploadRoute = AppUploadRouteImport.update({
  id: '/app/upload',
  path: '/app/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/app/settings',
  path: '/app/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/app/notes',
  path: '/app/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const AppJobleadsRoute = AppJobleadsRouteImport.update({
  id: '/app/jobleads',
  path: '/app/jobleads',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInterviewsRoute = AppInterviewsRouteImport.update({
  id: '/app/interviews',
  path: '/app/interviews',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/app/documents',
  path: '/app/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const AppApplicationsRoute = AppApplicationsRouteImport.update({
  id: '/app/applications',
  path: '/app/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AppApplicationRoute = AppApplicationRouteImport.update({
  id: '/app/application',
  path: '/app/application',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAddapplicationRoute = AppAddapplicationRouteImport.update({
  id: '/app/addapplication',
  path: '/app/addapplication',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/app/addapplication': typeof AppAddapplicationRoute
  '/app/application': typeof AppApplicationRoute
  '/app/applications': typeof AppApplicationsRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/interviews': typeof AppInterviewsRoute
  '/app/jobleads': typeof AppJobleadsRoute
  '/app/notes': typeof AppNotesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/upload': typeof AppUploadRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/app/addapplication': typeof AppAddapplicationRoute
  '/app/application': typeof AppApplicationRoute
  '/app/applications': typeof AppApplicationsRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/interviews': typeof AppInterviewsRoute
  '/app/jobleads': typeof AppJobleadsRoute
  '/app/notes': typeof AppNotesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/upload': typeof AppUploadRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/app/addapplication': typeof AppAddapplicationRoute
  '/app/application': typeof AppApplicationRoute
  '/app/applications': typeof AppApplicationsRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/interviews': typeof AppInterviewsRoute
  '/app/jobleads': typeof AppJobleadsRoute
  '/app/notes': typeof AppNotesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/upload': typeof AppUploadRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/features'
    | '/how-it-works'
    | '/sign-in'
    | '/sign-up'
    | '/app/addapplication'
    | '/app/application'
    | '/app/applications'
    | '/app/documents'
    | '/app/interviews'
    | '/app/jobleads'
    | '/app/notes'
    | '/app/settings'
    | '/app/upload'
    | '/app'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/features'
    | '/how-it-works'
    | '/sign-in'
    | '/sign-up'
    | '/app/addapplication'
    | '/app/application'
    | '/app/applications'
    | '/app/documents'
    | '/app/interviews'
    | '/app/jobleads'
    | '/app/notes'
    | '/app/settings'
    | '/app/upload'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/features'
    | '/how-it-works'
    | '/sign-in'
    | '/sign-up'
    | '/app/addapplication'
    | '/app/application'
    | '/app/applications'
    | '/app/documents'
    | '/app/interviews'
    | '/app/jobleads'
    | '/app/notes'
    | '/app/settings'
    | '/app/upload'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  FeaturesRoute: typeof FeaturesRoute
  HowItWorksRoute: typeof HowItWorksRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  AppAddapplicationRoute: typeof AppAddapplicationRoute
  AppApplicationRoute: typeof AppApplicationRoute
  AppApplicationsRoute: typeof AppApplicationsRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppInterviewsRoute: typeof AppInterviewsRoute
  AppJobleadsRoute: typeof AppJobleadsRoute
  AppNotesRoute: typeof AppNotesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUploadRoute: typeof AppUploadRoute
  AppIndexRoute: typeof AppIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/upload': {
      id: '/app/upload'
      path: '/app/upload'
      fullPath: '/app/upload'
      preLoaderRoute: typeof AppUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/notes': {
      id: '/app/notes'
      path: '/app/notes'
      fullPath: '/app/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/jobleads': {
      id: '/app/jobleads'
      path: '/app/jobleads'
      fullPath: '/app/jobleads'
      preLoaderRoute: typeof AppJobleadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/interviews': {
      id: '/app/interviews'
      path: '/app/interviews'
      fullPath: '/app/interviews'
      preLoaderRoute: typeof AppInterviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/app/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/applications': {
      id: '/app/applications'
      path: '/app/applications'
      fullPath: '/app/applications'
      preLoaderRoute: typeof AppApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/application': {
      id: '/app/application'
      path: '/app/application'
      fullPath: '/app/application'
      preLoaderRoute: typeof AppApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/addapplication': {
      id: '/app/addapplication'
      path: '/app/addapplication'
      fullPath: '/app/addapplication'
      preLoaderRoute: typeof AppAddapplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  FeaturesRoute: FeaturesRoute,
  HowItWorksRoute: HowItWorksRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  AppAddapplicationRoute: AppAddapplicationRoute,
  AppApplicationRoute: AppApplicationRoute,
  AppApplicationsRoute: AppApplicationsRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppInterviewsRoute: AppInterviewsRoute,
  AppJobleadsRoute: AppJobleadsRoute,
  AppNotesRoute: AppNotesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUploadRoute: AppUploadRoute,
  AppIndexRoute: AppIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
